<a href="https://colab.research.google.com/github/suisen26/AI/blob/main/%E3%83%A1%E3%82%BD%E3%83%83%E3%83%89%E4%B8%80%E8%A6%A7(numpy).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#<font color="red">numpyの関数

In [1]:
import numpy as np

In [2]:
_array_ = np.ndarray(shape=(2,2))

#<font color="red">arange()

In [3]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [4]:
np.arange(1, stop=10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.arange(1, stop=10, step=2)

array([1, 3, 5, 7, 9])

#<font color="red">linspace()

In [6]:
np.linspace(0, 10)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [7]:
np.linspace(0, 10, 30)

array([ 0.        ,  0.34482759,  0.68965517,  1.03448276,  1.37931034,
        1.72413793,  2.06896552,  2.4137931 ,  2.75862069,  3.10344828,
        3.44827586,  3.79310345,  4.13793103,  4.48275862,  4.82758621,
        5.17241379,  5.51724138,  5.86206897,  6.20689655,  6.55172414,
        6.89655172,  7.24137931,  7.5862069 ,  7.93103448,  8.27586207,
        8.62068966,  8.96551724,  9.31034483,  9.65517241, 10.        ])

#<font color="red">reshape()

In [8]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [9]:
np.arange(15).reshape((3, 5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [10]:
np.arange(15).reshape((5, 3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

#<font color="red">shape

In [11]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [12]:
np.arange(15).shape

(15,)

In [13]:
np.arange(15).reshape((5, 3)).shape

(5, 3)

#<font color="red">ndim

In [14]:
np.arange(15).ndim

1

In [15]:
np.arange(15).reshape((5, 3)).ndim

2

#<font color="red">dtype

In [16]:
np.arange(15).dtype

dtype('int64')

In [17]:
np.arange(15.0).dtype

dtype('float64')

#<font color="red">zeros

In [18]:
np.zeros(3)

array([0., 0., 0.])

In [19]:
np.zeros([3, 2])

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

#<font color="red">nonzero

In [20]:
np.nonzero([1, 2, 4, 0, 5, 6])

(array([0, 1, 2, 4, 5]),)

#<font color="red">eye()

In [21]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#<font color="red">random()

In [22]:
np.random.random((3, 3, 3))

array([[[7.00683822e-01, 8.08904102e-01, 9.20023732e-01],
        [3.69442945e-01, 8.01874248e-01, 1.56250938e-01],
        [9.85258839e-01, 3.04508887e-05, 4.73528694e-01]],

       [[6.12765110e-01, 4.53582515e-01, 1.94633390e-01],
        [6.38547224e-01, 1.11681152e-02, 5.32358286e-01],
        [5.84733172e-01, 7.38196906e-01, 1.50237692e-01]],

       [[2.79478318e-01, 5.50194909e-01, 8.48953540e-01],
        [8.65795552e-01, 4.22383814e-01, 9.18985739e-01],
        [6.44184451e-01, 2.92074433e-01, 5.58856118e-01]]])

In [23]:
np.random.random_sample((3, 3, 3))

array([[[0.57356521, 0.16273946, 0.91581111],
        [0.72503746, 0.05326843, 0.77166394],
        [0.4531967 , 0.92552881, 0.64912541]],

       [[0.79653964, 0.96016779, 0.35616278],
        [0.89491787, 0.39156593, 0.25392146],
        [0.07856762, 0.91486271, 0.64719061]],

       [[0.39515859, 0.37412736, 0.52405595],
        [0.93537451, 0.6154862 , 0.04609029],
        [0.15598545, 0.03813487, 0.90323819]]])

#<font color="red">randint()

In [24]:
np.random.randint(4)

1

In [25]:
np.random.randint(4, 12)

8

In [26]:
np.random.randint(4, 12, (3, 2))

array([[ 7,  6],
       [ 4,  5],
       [10,  4]])

#<font color="red">uniform()

In [27]:
np.random.uniform()

0.4268058944022788

In [28]:
np.random.uniform(0)

0.15411329163473286

In [29]:
np.random.uniform(0, 10)

2.217446629316292

In [30]:
np.random.uniform(0, 10, (2, 3))

array([[8.2986887 , 2.38496119, 4.83040612],
       [4.31483034, 5.69880784, 5.78019813]])

#<font color="red">min()

In [31]:
np.random.random_sample((3, 3, 3)).min()

0.0027207579968754336

#<font color="red">max()

In [32]:
np.random.random_sample((3, 3, 3)).max()

0.9977622997427685

#<font color="red">ones

In [33]:
np.ones([3, 5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

#<font color="red">pad()

In [34]:
arr = np.arange(1, 5)
arr

array([1, 2, 3, 4])

In [35]:
np.pad(arr, (1, 1))

array([0, 1, 2, 3, 4, 0])

In [36]:
np.pad(arr, (1, 2))

array([0, 1, 2, 3, 4, 0, 0])

In [37]:
np.pad(arr, (1, 1), mode='edge')

array([1, 1, 2, 3, 4, 4])

In [38]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [39]:
np.pad(np.ones((3, 3)), (2, 1))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 1., 1., 0.],
       [0., 0., 1., 1., 1., 0.],
       [0., 0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0.]])

#<font color="red">diag()

In [40]:
arr

array([1, 2, 3, 4])

In [41]:
np.diag(arr)

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [42]:
np.arange(0, 9).reshape((3, 3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [43]:
np.diag(np.arange(0, 9).reshape((3, 3)))

array([0, 4, 8])

In [44]:
np.diag(np.arange(0, 9).reshape((3, 3)), k=1)

array([1, 5])

In [45]:
np.diag(np.arange(0, 9).reshape((3, 3)), k=-1)

array([3, 7])

#<font color="red">unravel_index()

In [46]:
arr = np.arange(0, 15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [47]:
np.unravel_index(5, (3, 4, 2))

(0, 2, 1)

In [48]:
np.unravel_index(np.argmax(arr), arr.shape)

(2, 4)

#<font color="red">dot()

In [49]:
np.dot(10, 2)

20

In [50]:
np.dot([1, 2], [3, 5])

13

#<font color="red">sqrt()

In [51]:
np.emath.sqrt(10)

3.1622776601683795

In [52]:
np.emath.sqrt(-10)

3.1622776601683795j

#<font color="red">meshgrid()

In [53]:
np.meshgrid([1, 2, 3], [4, 5, 6])

[array([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]]), array([[4, 4, 4],
        [5, 5, 5],
        [6, 6, 6]])]

#<font color="red">ndenumerate()

In [54]:
for i in np.ndenumerate([1, 2, 4]):
  print(i)

((0,), 1)
((1,), 2)
((2,), 4)


In [55]:
for i in np.ndenumerate(np.arange(0, 9).reshape(3, 3)):
  print(i)

((0, 0), 0)
((0, 1), 1)
((0, 2), 2)
((1, 0), 3)
((1, 1), 4)
((1, 2), 5)
((2, 0), 6)
((2, 1), 7)
((2, 2), 8)


#<font color="red">choice()

In [56]:
np.random.choice([1, 2, 3, 4, 5, 6])

2

#<font color="red">bincount()

In [57]:
np.bincount([1, 1, 2, 4, 5, 3, 2])

array([0, 2, 2, 1, 1, 1])